version: '2'
services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD:
      POSTGRES_DATABASE: come_across
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/come_across"
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: postgres
      DB_NAME: come_across
      DB_PAWWORD:
      DB_HOST: db

