version: '2'
services:
  webpacker:
    image: ${DOCKER_IMAGE_NAME-docker1.2}
    command: ["./scripts/start_webpack_dev.sh"]
    volumes:
      - .:/opt/docker1.2:cached
    ports:
      - 3035:3035 
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD:
      POSTGRES_DATABASE: come_across
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
  app:
    build: .
    command: ["./scripts/wait-for-it.sh", "db:5432", "--", "./scripts/start_rails.sh"]
    volumes:
      - .:/opt/docker1.2:cached
    ports:
      - "3001:3000"
    depends_on:
      - db
      - webpacker
    links:
      - db
      - webpacker
    environment:
      DB_USER: postgres
      DB_NAME: come_across
      DB_PAWWORD:
      DB_HOST: db

